version: '3'

services:
  psql:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=client.store.svc
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
