version: '3'

services:
  psql:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=client.store.svc
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  client.store.svc:
    image: bailey/client.store.svc:latest
    links:
      - "psql:psql"
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_HOST=psql
      - DB_NAME=client.store.svc
      - DB_SSL_MODE=disable
    ports:
      - "127.0.0.1:3000:3000"
